### ISSUE TITLE
Cross Compiling Error

### ISSUE THREAD

**Issue by gunasekaran7** [snipsco/tensorflow-build#14]
I am trying to cross compile for imx6 platform using the custom tool chain which comes in poky build system. I am getting the following error,

> ERROR:

 >in target '//external:cc_toolchain': no such package '@local_config_cc//': Traceback (most recent call last):
>	File "/home/dhivakar/.cache/bazel/_bazel_guna007/eaca9be522ab34626fd843800faf07ed/external/bazel_tools/tools/cpp/cc_configure.bzl", line 584
>		_find_cc(repository_ctx)
>	File "/home/dhivakar/.cache/bazel/_bazel_guna007/eaca9be522ab34626fd843800faf07ed/external/bazel_tools/tools/cpp/cc_configure.bzl", line 383, in _find_cc
>		repository_ctx.which(cc_name)

**Comment by fredszaq** [comment]
Hi ! 
which version of tensorflow are you tring to build ? the code on master has been tested with `v1.2.0` and bazel version `0.4.3`
I didn't try to compile it yet with a poky toolchain, however, on imx7d platform the binaries compiled with the raspi toolchain (the one used in the `compile-arm.sh` script) do work
If you manage to get it to work with the poky toolchain, please do not hesitate to do a PR :)
